# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1167b0593b3b55846b5d39e437504d3c5620e743d25198e7a0dce1530a05eb7c635335510826e96abfe1a69b0496f014d11e9968f356dcf8c2fb3f434299af

test:
  secret_key_base: 9c1323d6f2a68457740c67b7703932fd5314f07f32810016dd151e0ebe472b355e6638f4030fb479016e76595a450f67347fddd1f77880e3948e4442acec01ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
